"""Delivery evidence: diff parsing, filtering, chunking, compaction, test
logs, excerpts, budgets and the delivery input schema.  No network."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from jevgate.delivery import evidence as ev
from jevgate.delivery.schema import normalise_delivery, validate_delivery
from jevgate.textstats import tokens

DATA = Path(__file__).parent / "data" / "evidence"


def read(name: str) -> str:
    return (DATA / name).read_text(encoding="utf-8")


def make_diff(path: str, hunk_sizes: list[int], width: int = 28, status: str = "modified") -> str:
    """A synthetic git diff for ``path`` with one added-lines hunk per size."""
    header = [f"diff --git a/{path} b/{path}", "index 1111111..2222222 100644", f"--- a/{path}", f"+++ b/{path}"]
    body: list[str] = []
    start = 1
    for n, size in enumerate(hunk_sizes):
        body.append(f"@@ -{start},1 +{start},{size + 1} @@")
        body.append(" context")
        body.extend(f"+{n:02d}-{i:03d}-" + "x" * (width - 8) for i in range(size))
        start += 50
    return "\n".join(header + body) + "\n"


# ---------------------------------------------------------------------------
# parse_diff


def test_multi_file_diff_statuses_and_paths():
    files = ev.parse_diff(read("multi.diff"))
    by_path = {f.path: f for f in files}
    assert [f.path for f in files] == ["src/new_name.py", "src/added.py", "src/gone.py", "assets/logo.png", "src/mod.py"]
    renamed = by_path["src/new_name.py"]
    assert (renamed.status, renamed.old_path, len(renamed.hunks)) == ("renamed", "src/old_name.py", 1)
    assert by_path["src/added.py"].status == "added" and by_path["src/added.py"].old_path is None
    assert by_path["src/gone.py"].status == "deleted"
    binary = by_path["assets/logo.png"]
    assert binary.status == "binary" and binary.binary and binary.hunks == []
    mod = by_path["src/mod.py"]
    assert mod.status == "modified" and len(mod.hunks) == 2
    assert (mod.hunks[0].old_start, mod.hunks[0].old_count, mod.hunks[0].new_start, mod.hunks[0].new_count) == (10, 7, 10, 8)
    assert mod.hunks[0].header.endswith("@@ def compute(x):")
    assert mod.hunks[0].lines[2] == "+    b = a * 3"
    assert mod.tokens == tokens(mod.patch, "code")
    assert "".join(f.patch for f in files).count("diff --git") == 5


def test_crlf_diff_is_normalised():
    text = read("multi.diff").replace("\n", "\r\n")
    files = ev.parse_diff(text)
    assert len(files) == 5
    assert "\r" not in files[0].patch
    assert files[4].hunks[0].lines[2] == "+    b = a * 3"


def test_no_newline_marker_and_hunk_without_counts():
    text = (
        "diff --git a/x.txt b/x.txt\n--- a/x.txt\n+++ b/x.txt\n"
        "@@ -1 +1 @@\n-old\n\\ No newline at end of file\n+new\n\\ No newline at end of file\n"
    )
    (file,) = ev.parse_diff(text)
    hunk = file.hunks[0]
    assert (hunk.old_start, hunk.old_count, hunk.new_start, hunk.new_count) == (1, 1, 1, 1)
    assert hunk.lines == ["-old", "\\ No newline at end of file", "+new", "\\ No newline at end of file"]
    assert file.status == "modified"


def test_git_binary_patch_and_plain_unified_diff():
    text = "diff --git a/img.bin b/img.bin\nnew file mode 100644\nGIT binary patch\nliteral 3\nKc$~\n"
    (file,) = ev.parse_diff(text)
    assert file.status == "binary" and file.binary and file.path == "img.bin"
    plain = "--- a/one.py\n+++ b/one.py\n@@ -1,2 +1,2 @@\n-a\n+b\n c\n--- /dev/null\n+++ b/two.py\n@@ -0,0 +1 @@\n+z\n"
    files = ev.parse_diff(plain)
    assert [(f.path, f.status) for f in files] == [("one.py", "modified"), ("two.py", "added")]


def test_parse_diff_never_raises_and_keeps_unknown_lines():
    assert ev.parse_diff("") == []
    assert ev.parse_diff("not a diff\nat all\n") == []
    odd = "diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -1,2 +1,2 @@\n-a\nweird line\n+b\n"
    (file,) = ev.parse_diff(odd)
    assert "weird line" in file.patch and file.hunks[0].lines == ["-a", "weird line", "+b"]
    (anon,) = ev.parse_diff("@@ -1 +1 @@\n-a\n+b\n")
    assert anon.path == "(unknown)" and len(anon.hunks) == 1


# ---------------------------------------------------------------------------
# filter_files


def test_filter_files_reasons():
    generated = (
        "diff --git a/gen/api_pb.py b/gen/api_pb.py\nnew file mode 100644\n--- /dev/null\n+++ b/gen/api_pb.py\n"
        "@@ -0,0 +1,3 @@\n+# Code generated by protoc. DO NOT EDIT.\n+x = 1\n+y = 2\n"
    )
    not_generated = (
        "diff --git a/src/app.py b/src/app.py\n--- a/src/app.py\n+++ b/src/app.py\n"
        "@@ -10,2 +10,3 @@\n a\n+generated_at = now()\n b\n"
    )
    files = ev.parse_diff(
        read("multi.diff") + generated + not_generated
        + make_diff("package-lock.json", [3]) + make_diff("static/app.min.js", [3])
        + make_diff("dist/bundle.js", [3]) + make_diff("src/huge.py", [400])
    )
    kept, dropped = ev.filter_files(files, ignore=["*.min.js", "dist/*"], max_file_tokens=2000)
    reasons = {d["path"]: d["dropped_reason"] for d in dropped}
    assert reasons == {
        "assets/logo.png": "binary", "gen/api_pb.py": "generated", "package-lock.json": "lockfile",
        "static/app.min.js": "ignored", "dist/bundle.js": "ignored", "src/huge.py": "too_large",
    }
    assert {f.path for f in kept} == {"src/new_name.py", "src/added.py", "src/gone.py", "src/mod.py", "src/app.py"}
    huge = next(d for d in dropped if d["path"] == "src/huge.py")
    assert huge["tokens"] > 2000 and huge["status"] == "modified"


def test_ignored_matches_path_suffixes():
    assert ev.ignored("web/static/app.min.js", ["*.min.js"])
    assert ev.ignored("packages/ui/dist/index.js", ["dist/*"])
    assert not ev.ignored("src/dist_utils.py", ["dist/*"])
    assert ev.DEFAULT_LOCKFILES[0] == "package-lock.json" and "uv.lock" in ev.DEFAULT_LOCKFILES


# ---------------------------------------------------------------------------
# chunk_file


def test_chunk_single_when_within_budget():
    (file,) = ev.parse_diff(make_diff("a.py", [5, 5]))
    (chunk,) = ev.chunk_file(file, 10_000)
    assert (chunk.index, chunk.total, chunk.truncated) == (1, 1, False)
    assert chunk.patch == file.patch and chunk.tokens == file.tokens


def test_chunk_greedy_whole_hunks():
    (file,) = ev.parse_diff(make_diff("a.py", [10, 10, 10, 10, 10]))
    hunk_cost = tokens(file.hunks[0].text + "\n", "code")
    header_cost = tokens(file.header + "\n", "code")
    budget = header_cost + 2 * hunk_cost + 2  # two hunks fit, three do not
    chunks = ev.chunk_file(file, budget)
    assert [c.index for c in chunks] == [1, 2, 3] and all(c.total == 3 for c in chunks)
    assert [c.patch.count("@@ -") for c in chunks] == [2, 2, 1]
    assert all(c.patch.startswith("diff --git a/a.py b/a.py\n") and "+++ b/a.py" in c.patch for c in chunks)
    assert all(not c.truncated and c.tokens <= budget for c in chunks)
    assert "+04-009-" in chunks[2].patch


def test_chunk_truncates_oversized_hunk_with_marker():
    (file,) = ev.parse_diff(make_diff("big.py", [200]))
    budget = 300
    (chunk,) = ev.chunk_file(file, budget)
    assert chunk.truncated and chunk.tokens <= budget
    lines = chunk.patch.split("\n")
    assert lines[0] == "diff --git a/big.py b/big.py" and lines[3] == "+++ b/big.py" and lines[4].startswith("@@ ")
    assert lines[-1].startswith("[... ") and lines[-1].endswith(" lines omitted ...]")
    omitted = int(lines[-1].split()[1])
    assert omitted + (len(lines) - 5) == len(file.hunks[0].lines) + 1  # hunk header + body


def test_chunk_mixed_oversized_and_small_hunks():
    (file,) = ev.parse_diff(make_diff("m.py", [3, 200, 3]))
    header_cost = tokens(file.header + "\n", "code")
    small_cost = tokens(file.hunks[0].text + "\n", "code")
    chunks = ev.chunk_file(file, header_cost + 2 * small_cost + 20)
    assert [c.truncated for c in chunks] == [False, True, False]
    assert all(c.patch.startswith("diff --git") for c in chunks)


# ---------------------------------------------------------------------------
# compact_diff


def test_compact_diff_levels():
    files = ev.parse_diff(make_diff("a.py", [30]) + make_diff("b.py", [5]))
    full = "\n".join(f.patch for f in files)
    assert ev.compact_diff(files, tokens(full, "code")) == (full, False)

    text, compacted = ev.compact_diff(files, tokens(full, "code") - 1)
    assert compacted and "[... 11 more lines ...]" in text  # 31 body lines, 20 kept
    a_part, b_part = text.split("diff --git a/b.py b/b.py")
    assert a_part.count("+00-") == 19 and " context" in a_part  # 20 kept lines: context + 19 added
    assert b_part.count("+00-") == 5 and "more lines" not in b_part
    assert text.startswith("diff --git a/a.py b/a.py\n--- a/a.py\n+++ b/a.py\n@@ ")

    headers_only, compacted = ev.compact_diff(files, tokens(text, "code") - 1)
    assert compacted and "@@ -1,1 +1,31 @@" in headers_only and "+00-" not in headers_only
    assert "diff --git a/b.py b/b.py" in headers_only

    listing, compacted = ev.compact_diff(files, 5)
    assert compacted and listing == "a.py (modified)\nb.py (modified)"


# ---------------------------------------------------------------------------
# parse_test_log


def test_pytest_log():
    log = ev.parse_test_log("pytest.log", read("pytest.log"))
    assert log.tool == "pytest"
    assert (log.passed, log.failed, log.skipped, log.errors) == (2, 1, 1, 1)
    assert log.failing == ["tests/test_math.py::test_div", "tests/test_io.py::test_read"]
    assert len(log.names) == 5 and "tests/test_math.py::test_skip" in log.names
    assert log.summary == "1 failed, 2 passed, 1 skipped, 1 error in 0.12s"
    assert len(log.failing_blocks) == 2
    assert log.failing_blocks[1].startswith("___") and "ZeroDivisionError" in log.failing_blocks[1]
    assert log.sha256 == hashlib.sha256(read("pytest.log").encode()).hexdigest()
    assert log.tail.endswith("in 0.12s ==================") and len(log.tail.splitlines()) <= 40


def test_pytest_summary_only_log():
    text = "===== test session starts =====\ncollected 3 items\n\n...\n\n===== 3 passed in 0.01s =====\n"
    log = ev.parse_test_log("t.log", text)
    assert log.tool == "pytest" and (log.passed, log.failed, log.skipped, log.errors) == (3, 0, 0, 0)
    assert log.failing == [] and log.failing_blocks == []


def test_unittest_log():
    log = ev.parse_test_log("unittest.log", read("unittest.log"))
    assert log.tool == "unittest"
    assert (log.passed, log.failed, log.skipped, log.errors) == (1, 1, 1, 1)
    assert log.failing == ["tests.test_math.MathTest.test_div", "tests.test_io.IoTest.test_read"]
    assert len(log.names) == 4
    assert log.summary == "Ran 4 tests: FAILED (failures=1, errors=1, skipped=1)"
    assert [b.split("\n")[0] for b in log.failing_blocks] == [
        "ERROR: test_read (tests.test_io.IoTest)", "FAIL: test_div (tests.test_math.MathTest)",
    ]
    assert "AssertionError: 1 != 2" in log.failing_blocks[1]


def test_unittest_ok_with_skips():
    log = ev.parse_test_log("u.log", ".s\n----------------------------------------------------------------------\nRan 2 tests in 0.001s\n\nOK (skipped=1)\n")
    assert log.tool == "unittest" and (log.passed, log.failed, log.skipped, log.errors) == (1, 0, 1, 0)


def test_jest_log():
    log = ev.parse_test_log("jest.log", read("jest.log"))
    assert log.tool == "jest"
    assert (log.passed, log.failed, log.skipped, log.errors) == (3, 1, 1, 0)
    assert log.failing == ["Calculator › divides numbers"]
    assert log.names == ["adds numbers", "divides numbers", "multiplies numbers"]
    assert log.summary == "Tests:       1 failed, 1 skipped, 3 passed, 5 total"
    assert len(log.failing_blocks) == 1 and "Expected: 2" in log.failing_blocks[0]


def test_go_log():
    log = ev.parse_test_log("go.log", read("go.log"))
    assert log.tool == "go"
    assert (log.passed, log.failed, log.skipped, log.errors) == (1, 1, 1, 0)
    assert log.failing == ["TestDivide"]
    assert log.names == ["TestAdd", "TestDivide", "TestSkip"]
    assert log.summary == "packages: 1 ok, 1 FAIL; tests: 1 passed, 1 failed, 1 skipped"
    assert log.failing_blocks == ["=== RUN   TestDivide\n    calc_test.go:15: expected 2, got 3\n--- FAIL: TestDivide (0.00s)"]


def test_cargo_log():
    log = ev.parse_test_log("cargo.log", read("cargo.log"))
    assert log.tool == "cargo"
    assert (log.passed, log.failed, log.skipped, log.errors) == (1, 1, 1, None)
    assert log.failing == ["tests::divide"]
    assert log.names == ["tests::add", "tests::divide", "tests::slow"]
    assert log.summary.startswith("test result: FAILED. 1 passed; 1 failed; 1 ignored")
    assert len(log.failing_blocks) == 1 and log.failing_blocks[0].startswith("---- tests::divide stdout ----")
    assert "panicked" in log.failing_blocks[0]


def test_unknown_and_empty_logs():
    text = 'ran test_alpha and TestBeta\nit("does the thing", () => {})\nall good\n'
    log = ev.parse_test_log("x.log", text)
    assert log.tool == "unknown"
    assert (log.passed, log.failed, log.skipped, log.errors) == (None, None, None, None)
    assert log.names == ["test_alpha", "TestBeta", "does the thing"]
    assert log.failing == [] and log.failing_blocks == [] and log.summary is None
    assert log.tail == text.rstrip("\n") and log.tokens == tokens(text, "code")
    empty = ev.parse_test_log("empty.log", "")
    assert empty.tool == "unknown" and empty.tail == "" and empty.names == [] and empty.tokens == 0
    assert empty.sha256 == hashlib.sha256(b"").hexdigest()


def test_log_caps_blocks_and_names():
    lines = [f"tests/t.py::test_{i} PASSED" for i in range(400)]
    lines += ["=== FAILURES ===", "____ test_0 ____"] + [f"line {i}" for i in range(300)]
    lines += ["=== 400 passed in 1s ==="]
    log = ev.parse_test_log("big.log", "\n".join(lines))
    assert len(log.names) == 300
    assert sum(b.count("\n") + 1 for b in log.failing_blocks) <= 200
    assert log.failing_blocks[0].endswith("lines omitted ...]")
    assert len(log.tail.splitlines()) == 40


# ---------------------------------------------------------------------------
# tests_state


def make_log(path: str = "t.log", *, tail_lines: int = 200, names: int = 80, blocks: int = 2) -> ev.TestLog:
    return ev.TestLog(
        path=path, tool="pytest", passed=names, failed=1, skipped=0, errors=0,
        failing=["tests/t.py::test_zero"],
        failing_blocks=["\n".join(f"block{b} line {i:02d} {'y' * 16}" for i in range(10)) for b in range(blocks)],
        names=[f"test_module_alpha_case_number_{i:04d}" for i in range(names)],
        summary="1 failed, 80 passed in 1.0s",
        tail="\n".join(f"tail line {i:03d} " + "z" * 46 for i in range(tail_lines)),
        sha256="0" * 64, tokens=1,
    )


def state_tokens(state: dict) -> int:
    return tokens(json.dumps(state, ensure_ascii=False), "code")


def test_tests_state_merges_and_fits_without_trimming():
    log = make_log()
    state = ev.tests_state([log], 10**6)
    assert state["tool"] == "pytest" and state["counts"] == {"passed": 80, "failed": 1, "skipped": 0, "errors": 0}
    assert state["names"] == log.names and state["failing_blocks"] == log.failing_blocks and state["tail"] == log.tail
    assert state["failing"] == log.failing and state["summary"] == log.summary
    two = ev.tests_state([log, make_log("go.log")], 10**6)
    assert two["counts"]["passed"] == 160 and "--- go.log ---" in two["tail"]
    assert two["summary"].startswith("t.log: ") and two["names"] == log.names
    empty = ev.tests_state([], 100)
    assert empty["tool"] == "none" and empty["counts"]["passed"] is None and empty["names"] == []


def test_tests_state_trim_order_tail_names_blocks():
    log = make_log()
    untrimmed = ev.tests_state([log], 10**6)
    tail_cost = tokens(json.dumps(untrimmed["tail"]), "code")
    names_cost = tokens(json.dumps(untrimmed["names"]), "code")
    blocks_cost = tokens(json.dumps(untrimmed["failing_blocks"]), "code")
    assert tail_cost > 3 * names_cost > 3 * blocks_cost  # sizes chosen so each stage is distinct

    only_tail = ev.tests_state([log], 1600)
    assert state_tokens(only_tail) <= 1600
    assert only_tail["tail"].startswith("[... ") and "lines trimmed ...]" in only_tail["tail"]
    assert only_tail["tail"].endswith(log.tail.splitlines()[-1])
    assert only_tail["names"] == log.names and only_tail["failing_blocks"] == log.failing_blocks

    tail_and_names = ev.tests_state([log], 700)
    assert state_tokens(tail_and_names) <= 700
    assert tail_and_names["tail"] == "[... 200 lines trimmed ...]"
    assert len(tail_and_names["names"]) < len(log.names) and tail_and_names["names"][-1].startswith("[... ")
    assert tail_and_names["names"][-1].endswith(" more names ...]")
    assert tail_and_names["failing_blocks"] == log.failing_blocks

    everything = ev.tests_state([log], 150)
    assert state_tokens(everything) <= 150
    assert everything["names"] == ["[... 80 more names ...]"]
    assert everything["failing_blocks"] != log.failing_blocks
    assert "lines of failure output trimmed ...]" in everything["failing_blocks"][-1]
    assert everything["failing"] == log.failing and everything["counts"] == untrimmed["counts"]


# ---------------------------------------------------------------------------
# read_excerpt / files_after_state


def test_read_excerpt_with_and_without_range(tmp_path):
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "mod.py").write_text("l1\nl2\nl3\nl4\nl5\n")
    whole = ev.read_excerpt(tmp_path, "pkg/mod.py")
    assert whole == {"path": "pkg/mod.py", "range": None, "text": "l1\nl2\nl3\nl4\nl5\n"}
    part = ev.read_excerpt(tmp_path, "pkg/mod.py:2-4")
    assert part == {"path": "pkg/mod.py", "range": [2, 4], "text": "l2\nl3\nl4"}
    assert ev.read_excerpt(tmp_path, "pkg/mod.py:3") == {"path": "pkg/mod.py", "range": [3, 3], "text": "l3"}
    assert ev.read_excerpt(tmp_path, "pkg/mod.py:4-99")["range"] == [4, 5]
    absolute = ev.read_excerpt(tmp_path / "elsewhere", str(tmp_path / "pkg" / "mod.py") + ":1-1")
    assert absolute["text"] == "l1"
    with pytest.raises(ev.EvidenceError, match="no such file"):
        ev.read_excerpt(tmp_path, "pkg/missing.py")
    with pytest.raises(ev.EvidenceError, match="START <= END"):
        ev.read_excerpt(tmp_path, "pkg/mod.py:4-2")
    with pytest.raises(ev.EvidenceError, match="past the end"):
        ev.read_excerpt(tmp_path, "pkg/mod.py:9-12")


def test_files_after_state_trims_largest_with_marker():
    big = {"path": "big.py", "range": None, "text": "\n".join(f"line {i:03d} " + "w" * 50 for i in range(100))}
    small = {"path": "small.py", "range": [1, 5], "text": "\n".join(f"s{i}" for i in range(5))}
    untouched = ev.files_after_state([big, small], 10**6)
    assert untouched == [big, small]
    trimmed = ev.files_after_state([big, small], 1200)
    assert state_tokens(trimmed) <= 1200
    assert trimmed[1] == small
    assert trimmed[0]["path"] == "big.py" and trimmed[0]["range"] is None
    assert trimmed[0]["text"].endswith("[... 50 lines omitted ...]") and trimmed[0]["text"].startswith("line 000 ")
    assert ev.files_after_state([], 10) == []


# ---------------------------------------------------------------------------
# assert_budget


def test_assert_budget_names_largest_key():
    questions = {"q1": {"instructions": "Is it fine?", "options": ["yes", "no"]}}
    ev.assert_budget({"ticket": "t", "diff": "a" * 3000}, questions)
    with pytest.raises(ev.EvidenceError, match=r"state too large.*largest state key is 'diff'"):
        ev.assert_budget({"ticket": "t", "diff": "a" * 90_000}, questions)
    many = {f"q{i}": {"instructions": "x" * 40_000} for i in range(5)}  # ~10k prose tokens each
    state = {"ticket": "t", "tests": "b" * 55_000}  # ~18.3k tokens: under the state limit with one question
    with pytest.raises(ev.EvidenceError, match=r"request too large.*largest state key is 'tests'"):
        ev.assert_budget(state, many)
    ev.assert_budget(state, many, request_limit=100_000)


# ---------------------------------------------------------------------------
# git


def _git(repo: Path, *args: str) -> str:
    env = {
        **os.environ, "HOME": str(repo), "GIT_CONFIG_GLOBAL": str(repo / "no-global-config"),
        "GIT_CONFIG_NOSYSTEM": "1", "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
        "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com",
    }
    return subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True, env=env).stdout


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    if not shutil.which("git"):
        pytest.skip("git not installed")
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "symbolic-ref", "HEAD", "refs/heads/main")
    (tmp_path / "a.txt").write_text("one\ntwo\n")
    _git(tmp_path, "add", "a.txt")
    _git(tmp_path, "commit", "-q", "-m", "init")
    return tmp_path


def test_git_diff_working_tree_and_untracked(repo: Path):
    (repo / "a.txt").write_text("one\ntwo\nthree\n")
    (repo / "b.txt").write_text("new\n")
    text = ev.git_diff(repo, "HEAD")
    (file,) = ev.parse_diff(text)
    assert file.path == "a.txt" and file.status == "modified" and "+three" in file.patch
    assert ev.untracked_files(repo) == ["b.txt"]
    assert ev.git_diff(repo, "HEAD", "HEAD") == ""


def test_git_diff_merge_base_form(repo: Path):
    _git(repo, "checkout", "-q", "-b", "feature")
    (repo / "a.txt").write_text("one\ntwo\nfeature\n")
    _git(repo, "commit", "-q", "-am", "feature work")
    _git(repo, "checkout", "-q", "main")
    (repo / "c.txt").write_text("main moved on\n")
    _git(repo, "add", "c.txt")
    _git(repo, "commit", "-q", "-m", "main work")
    files = ev.parse_diff(ev.git_diff(repo, "main", "feature"))
    assert [f.path for f in files] == ["a.txt"] and "+feature" in files[0].patch
    assert ev.untracked_files(repo) == []


def test_git_errors_raise_evidence_error(repo: Path, tmp_path_factory: pytest.TempPathFactory):
    with pytest.raises(ev.EvidenceError, match="no-such-ref"):
        ev.git_diff(repo, "no-such-ref")
    outside = tmp_path_factory.mktemp("not-a-repo")
    with pytest.raises(ev.EvidenceError, match="not a git repository"):
        ev.untracked_files(outside)


# ---------------------------------------------------------------------------
# evidence_summary


def test_evidence_summary_shape():
    files = ev.parse_diff(read("multi.diff") + make_diff("big.py", [200]))
    kept, dropped = ev.filter_files(files, ignore=[], max_file_tokens=10_000)
    chunks = {f.path: ev.chunk_file(f, 300) for f in kept}
    log = ev.parse_test_log("pytest.log", read("pytest.log"))
    summary = ev.evidence_summary(kept, dropped, chunks, [log], compacted=True)
    assert summary["compacted"] is True
    by_path = {f["path"]: f for f in summary["files"]}
    assert by_path["big.py"]["chunks"] == 1 and by_path["big.py"]["truncated"] is True
    assert by_path["src/mod.py"] == {"path": "src/mod.py", "status": "modified", "tokens": 89, "chunks": 1, "truncated": False}
    assert by_path["assets/logo.png"]["dropped_reason"] == "binary" and by_path["assets/logo.png"]["chunks"] == 0
    assert summary["tests"] == [{
        "path": "pytest.log", "tool": "pytest", "passed": 2, "failed": 1, "skipped": 1, "errors": 1, "sha256": log.sha256,
    }]


# ---------------------------------------------------------------------------
# schema


def valid_doc() -> dict:
    return {
        "ticket": {"title": "Add login", "why": "Users need it", "what": "A form", "acceptance": ["Users can log in"]},
        "diff": {"base": "main", "head": None, "text": "diff --git a/x b/x\n"},
        "files_after": [{"path": "x.py", "range": [1, 3], "text": "a\nb\nc"}],
        "tests": [{"path": "t.log", "text": "1 passed", "sha256": hashlib.sha256(b"1 passed").hexdigest()}],
    }


def test_validate_delivery_accepts_valid_and_minimal():
    assert validate_delivery(valid_doc()) == []
    assert validate_delivery({"ticket": {"title": "T"}, "diff": {"text": ""}}) == []


def test_validate_delivery_lists_problems():
    assert validate_delivery([]) == ["delivery input must be a JSON object"]
    bad = {
        "ticket": {"title": " ", "why": 3, "acceptance": "not a list"},
        "diff": {"text": 5, "base": 1},
        "files_after": [{"path": "", "text": "x", "range": [3, 1]}, "nope"],
        "tests": [{"path": "t.log", "text": "abc", "sha256": "0" * 64}, {"path": "u.log", "text": "x", "sha256": "zz"}],
    }
    problems = validate_delivery(bad)
    expected_fragments = [
        "ticket.title", "ticket.why", "ticket.acceptance", "diff.text", "diff.base",
        "files_after[0].path", "files_after[0].range", "files_after[1]",
        "tests[0].sha256: does not match", "tests[1].sha256: must be 64 hex",
    ]
    for fragment in expected_fragments:
        assert any(fragment in p for p in problems), (fragment, problems)
    assert len(problems) == len(expected_fragments)
    assert validate_delivery({"diff": {"text": ""}}) == ["ticket: missing or not an object"]


def test_normalise_delivery_fills_defaults_and_dedupes():
    doc = {
        "ticket": {"title": "  T  ", "acceptance": ["- Users can log in", "users can  log in.", "", "* Second", "SECOND", 7]},
        "diff": {"text": "d"},
        "tests": [{"path": "t.log", "text": "1 passed"}, {"path": "u.log", "text": "x", "sha256": "f" * 64}],
        "extra": {"keep": True},
    }
    out = normalise_delivery(doc)
    assert out["ticket"] == {"title": "T", "why": "", "what": "", "acceptance": ["Users can log in", "Second"]}
    assert out["diff"] == {"base": None, "head": None, "text": "d"}
    assert out["files_after"] == []
    assert out["tests"][0]["sha256"] == hashlib.sha256(b"1 passed").hexdigest()
    assert out["tests"][1]["sha256"] == "f" * 64
    assert out["extra"] == {"keep": True} and doc["ticket"]["title"] == "  T  "
    full = normalise_delivery(valid_doc())
    assert full["files_after"] == [{"path": "x.py", "range": [1, 3], "text": "a\nb\nc"}]
    assert validate_delivery(full) == []
